<?php

namespace Database\Seeders;

use App\Models\courses;
use Illuminate\Database\Seeder;

class Course extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        courses::insert([
            [
                'name' => 'Dasar-dasar Pengembangan Web',
                'description' => 'Pelajari dasar-dasar HTML, CSS, dan JavaScript.',
                'price' => 200000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'JavaScript Lanjutan',
                'description' => 'Mendalami JavaScript dengan konsep lanjutan.',
                'price' => 300000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pengenalan Python',
                'description' => 'Pelajari dasar-dasar bahasa pemrograman Python.',
                'price' => 250000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Ilmu Data',
                'description' => 'Jelajahi dasar-dasar ilmu data dengan Python.',
                'price' => 500000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pengembangan Aplikasi Mobile dengan Flutter',
                'description' => 'Pelajari cara membangun aplikasi mobile lintas platform menggunakan Flutter.',
                'price' => 400000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'React JS untuk Pemula',
                'description' => 'Pelajari cara membuat aplikasi web dinamis dengan React JS.',
                'price' => 350000,
                'status' => 'inactive',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kelas Master Laravel',
                'description' => 'Menguasai framework Laravel untuk membangun aplikasi web yang kuat.',
                'price' => 450000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Pembelajaran Mesin',
                'description' => 'Memulai dengan konsep pembelajaran mesin dan AI.',
                'price' => 600000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Desain UI/UX',
                'description' => 'Pelajari dasar-dasar desain UI/UX untuk aplikasi web dan mobile.',
                'price' => 300000,
                'status' => 'inactive',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Keamanan Siber',
                'description' => 'Memahami dasar-dasar keamanan siber dan cara melindungi sistem.',
                'price' => 550000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Komputasi Awan',
                'description' => 'Pelajari dasar-dasar komputasi awan dan layanannya.',
                'price' => 450000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar DevOps',
                'description' => 'Memahami prinsip dan praktik DevOps.',
                'price' => 500000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Blockchain',
                'description' => 'Memulai dengan teknologi blockchain dan aplikasinya.',
                'price' => 600000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Kecerdasan Buatan untuk Pemula',
                'description' => 'Pelajari dasar-dasar kecerdasan buatan dan aplikasinya.',
                'price' => 700000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Analitik Data Besar',
                'description' => 'Jelajahi dasar-dasar data besar dan analitik.',
                'price' => 650000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Internet of Things (IoT)',
                'description' => 'Pelajari dasar-dasar IoT dan aplikasinya.',
                'price' => 550000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Pemasaran Digital',
                'description' => 'Memahami dasar-dasar pemasaran digital dan strateginya.',
                'price' => 400000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Peretasan Etis',
                'description' => 'Pelajari prinsip dan praktik peretasan etis.',
                'price' => 750000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Augmented Reality (AR)',
                'description' => 'Memulai dengan augmented reality dan aplikasinya.',
                'price' => 500000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Virtual Reality (VR)',
                'description' => 'Pelajari dasar-dasar virtual reality dan aplikasinya.',
                'price' => 550000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Pengembangan Game dengan Unity',
                'description' => 'Pelajari cara mengembangkan game menggunakan Unity.',
                'price' => 600000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Robotika untuk Pemula',
                'description' => 'Memulai dengan robotika dan aplikasinya.',
                'price' => 700000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'name' => 'Dasar-dasar Komputasi Kuantum',
                'description' => 'Pelajari dasar-dasar komputasi kuantum dan aplikasinya.',
                'price' => 800000,
                'status' => 'active',
                'student_count' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
